import type { Metadata } from "next";
import "./globals.css";
import  Provider  from "./_trpc/Provider";


export const metadata: Metadata = {
  title: "Video Player Vidext",
  description: "Generated by Diego Rubio",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
